### PR TITLE
Namespace rpc proto, update go-plugin

### LINKED ISSUE #12: Unable to get example plugin code from documentation working
Hi,

I'm trying to build the example code from https://docs.hashicorp.com/sentinel/extending/dev but am unable to get it to work so far.

The produced binary seems to be compiled to support netrpc only and not grpc:
```
2018-09-03T12:16:02.418Z [DEBUG] plugin: starting plugin: path=/usr/local/bin/sentinel-test args=[/usr/local/bin/sentinel-test]
2018-09-03T12:16:02.429Z [DEBUG] plugin: waiting for RPC address: path=/usr/local/bin/sentinel-test
2018-09-03T12:16:02.458Z [DEBUG] plugin.sentinel-test: plugin address: timestamp=2018-09-03T12:16:02.458Z address=/tmp/plugin485228174 network=unix
2018-09-03T12:16:02.461Z [DEBUG] plugin: plugin process exited: path=/usr/local/bin/sentinel-test
Runtime error while running the policy:

sentinel.policy:1:1: Unsupported plugin protocol "netrpc". Supported: [grpc]

A runtime error is a non-recoverable error and always represents a bug
in the policy. When a runtime error is experienced, the result of the
policy is "false". Please fix the error above and try again.

Execution trace. The information below will show the values of all
the rules evaluated and their intermediate boolean expressions. Note that
some boolean expressions may be missing if short-circuit logic was taken.


make: *** [all] Error 3
```

I am not sure why this is the case as I believe the sentinel-sdk should make the go-plugin library switch to using grpc since it has the line `GRPCServer: goplugin.DefaultGRPCServer,` @ https://github.com/hashicorp/sentinel-sdk/blob/master/rpc/serve.go#L46

I have created a [repository with the code that I am trying to build](https://github.com/endemics/sentinel-test), containing the instructions needed in the Readme file to reproduce the issue (I have vendored the dependencies and locked the sentinel binary version as well so it should be 100% reproduceable).

### PR DESCRIPTION
**Pull request by vancluever**
This does a couple of things:

* Namespaces our RPC protocol to `hashicorp.sentinel.proto`. This ensures
there are no conflicts with any of our other products, libraries, or
anything else that may try to use the global namespace.

* Updates the plugin interfaces so that the latest go-plugin can be used
correctly.

A new version of the Sentinel Simulator will follow soon that will support the new namespace set here.

Fixes #12.

### CODE REVIEW

**Comment by vancluever** [comment]
@dadgar ^^^

**Comment by mitchellh** [comment]
This looks good to me but would like to see Alex’s review too.

**Comment by dadgar** [comment]
LGTM

**Comment by vancluever** [comment]
🎉 going in now!

**Pull request merged**
