### PR TITLE
Add module support

### PR DESCRIPTION
**Pull request by vancluever**
This adds module support.

A bit of adjustment was required to the testing framework so that import path inference worked when modules are enabled. This is now done by testing using `go list` - `go list -m` to see if modules are enabled, and then, if they are, `go list` is run from within the working directory (or the directory supplied by `ImportPath` if that's supplied).

### CODE REVIEW

**Comment by jefferai** [comment]
Hi Chris! I've been working pretty deeply on modules for Serf, Vault, and Consul and will be working with Nomad and maybe Terraform soon too. I'm helping to figure out some of the common ways we want to structure modules and submodules and work with tags. I will try to look at this soon, but please do me a favor and don't tag anything past v0 before I can circle around to this (and Sentinel proper).

For the other projects we are on hold because we have found some things that don't work with Go < 1.12 due to bugs in the modules support. As a result for those at least we are waiting until 1.12 is fully released. That may not be the case with Sentinel; let's discuss at some point what your dev needs are since the main issue is related to dev workflows.

**Comment by vancluever** [comment]
:+1: @jefferai - yeah we have this tagged at v0.1.0 right now and there's no plans to 1.0 this for a while anyway, as is the case with any of the other (internal) Sentinel projects. I'll reach out offline!

**Comment by vancluever** [comment]
Merging this shortly due to timeout and the fact that we are moving other projects along with modules (namely the TF plugins and the Sentinel TFE worker). If you have any objections speak now 😉

**Comment by jefferai** [comment]
@vancluever You said you were going to reach out to me offline, so I didn't circle back to this, and thus haven't looked at it.

**Comment by jefferai** [comment]
@vancluever This seems fine but I'd urge caution before going ahead with more -- discussion about TF plugins has me a bit worried. For anything with more than even minor complexity I would suggest holding off until 1.12. We can talk more directly about the issues if you want.

**Pull request merged**
